### ISSUE TITLE
Incompatible with beets 2.4.0

### ISSUE THREAD

**Issue by justjakka** [gtronset/beets-filetote#211]
unfortunately plugin is broken on new beets version probably due to beets api changes

```
** error loading plugin filetote
Traceback (most recent call last):
  File "/home/jakka/.local/share/pipx/venvs/beets/lib/python3.11/site-packages/beets/plugins.py", line 368, in _get_plugin
    namespace = __import__(f"{PLUGIN_NAMESPACE}.{name}", None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jakka/.local/share/pipx/venvs/beets/lib/python3.11/site-packages/beetsplug/filetote.py", line 23, in <module>
    from beets.library import DefaultTemplateFunctions
ImportError: cannot import name 'DefaultTemplateFunctions' from 'beets.library' (/home/jakka/.local/share/pipx/venvs/beets/lib/python3.11/site-packages/beets/library/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jakka/.local/share/pipx/venvs/beets/lib/python3.11/site-packages/beets/plugins.py", line 370, in _get_plugin
    raise PluginImportError(name) from exc
beets.plugins.PluginImportError: Could not import plugin filetote
```

**Comment by bdrago** [comment]
I tried the changes from #204 but still got import errors. Anyone have luck getting this to work with beets 2.4.0?

**Comment by AchillesPDX** [comment]
Looking forward to getting this up and running. I'm setting up a new beets install to reorganize everything and not having my .lrc files get properly carried along and renamed is REALLY frustrating.

**Comment by AchillesPDX** [comment]
Hah. I think ChatGPT fixed it :D

Let me know if you want a copy of its code to check against your own. I know ChatGPT can create some SERIOUS garbage, but this seems to work for now.

**Comment by tcouture** [comment]
I tested the fix using [linuxserver/beets](https://github.com/linuxserver/docker-beets) V240-L288 on Unraid and it works great. Thanks guys.

**Comment by gtronset** [comment]
New version is in-progress. Unfortunately the changes in 2.4.0  impact my test setup and helpers which is requiring additional time to fix/refactor.

**Comment by gtronset** [comment]
Filetote was updated in [v1.1.1](https://github.com/gtronset/beets-filetote/releases/tag/v1.1.1) via #231 to allow newer Beets versions, which resolves this ticket. Thanks all for your patience!
