### ISSUE TITLE
Error when importing multidisc release with beets 2.13.1

### ISSUE THREAD

**Issue by Gwouigwoui** [gtronset/beets-filetote#362]
## Problem

Running this command in verbose (`-vv`) mode:

```console
beet -v import
```

Led to this problem / output:

```console
Traceback (most recent call last):
  File "/home/guillaume/.local/bin/beet", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/ui/__init__.py", line 966, in main
    _raw_main(args)
    ~~~~~~~~~^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/ui/__init__.py", line 903, in _raw_main
    subcommand.func(lib, suboptions, subargs)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/ui/commands/import_/__init__.py", line 132, in import_func
    import_files(lib, byte_paths, query)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/ui/commands/import_/__init__.py", line 76, in import_files
    session.run()
    ~~~~~~~~~~~^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/importer/session.py", line 237, in run
    pl.run_parallel(QUEUE_SIZE)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/util/pipeline.py", line 534, in run_parallel
    raise exc.with_traceback(exc_info[2])
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/util/pipeline.py", line 420, in run
    self._run_in_context(self.coro.send, msg)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/util/pipeline.py", line 263, in _run_in_context
    return self.ctx.run(func, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/util/pipeline.py", line 198, in coro
    task = func(*args, task)
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/importer/stages.py", line 293, in manipulate_files
    task.manipulate_files(
    ~~~~~~~~~~~~~~~~~~~~~^
        session=session,
        ^^^^^^^^^^^^^^^^
        operation=operation,
        ^^^^^^^^^^^^^^^^^^^^
        write=session.config["write"].get(bool),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/importer/tasks.py", line 482, in manipulate_files
    item.move(operation)
    ~~~~~~~~~^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/library/models.py", line 1199, in move
    self.move_file(dest, operation)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/library/models.py", line 1047, in move_file
    plugins.send(
    ~~~~~~~~~~~~^
        "before_item_moved",
        ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        destination=dest,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/plugins.py", line 626, in send
    if (r := handler(**arguments)) is not None
             ~~~~~~~^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beets/plugins.py", line 303, in wrapper
    return func(*args, **kwargs)
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beetsplug/filetote.py", line 248, in file_event_function
    self.file_operation_event_listener(event, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beetsplug/filetote.py", line 405, in file_operation_event_listener
    self.collect_artifacts(item, source_path, destination_path)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beetsplug/filetote.py", line 654, in collect_artifacts
    if beets_item.disctotal > 1 and path_utils.is_multidisc(source_path):
                                    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beetsplug/path_utils.py", line 155, in is_multidisc
    return any(pat.match(path_name_bytes) for pat in MULTIDISC_PATTERNS)
           ^^^
  File "/home/guillaume/.local/share/pipx/venvs/beets/lib/python3.14/site-packages/beetsplug/path_utils.py", line 155, in <genexpr>
    return any(pat.match(path_name_bytes) for pat in MULTIDISC_PATTERNS)
               ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```

My expectation was: smooth importing. The issue appeared with the new beets version.
___

## Setup

* OS: Ubuntu WSL 26.04
* Python version: 3.14.4
* beets version: 2.13.1
* Filetote version: 1.3.6

**Comment by CaptainStormfield** [comment]
Confirming this on beets 2.13.1 / filetote 1.3.6 / Python 3.13.2 / Windows 11.

Worth flagging that this isn't the only 2.13 incompatibility — it's the first of three on the
same code path. Each fix just moves the crash one step further down, so anyone patching only
`is_multidisc` will hit the next one immediately.

### 1. `path_utils.is_multidisc` — the error reported above

beets 2.13 compiles `MULTIDISC_PATTERNS` from `str` and moved the bytes variants to a new
`MULTIDISC_BYTES_PATTERNS`, so matching `bytestring_path(...)` against them raises
`TypeError: cannot use a string pattern on a bytes-like object`.

### 2. `path_utils.discover_artifacts` — `AttributeError` in `sorted_walk`

```
File "beetsplug/path_utils.py", line 54, in discover_artifacts
  for root, _dirs, files in util.sorted_walk(source_path, ignore=ignore)
File "beets/util/__init__.py", line 253, in sorted_walk
  sort_key = path.__class__.lower
AttributeError: type object 'WindowsPath' has no attribute 'lower'
```

`sorted_walk` is now generic over `AnyStr` and no longer coerces its argument, so the `Path`
it's handed flows through to `path.__class__.lower`. Verified directly against 2.13.1:

| argument | result |
|---|---|
| `Path`  | `AttributeError` |
| `bytes` | OK |
| `str`   | OK |

**This one isn't multi-disc specific.** `discover_artifacts` is called for every collection, so
any import that reaches artifact discovery fails on 2.13 — multi-disc releases just hit
`is_multidisc` first and crash earlier.

Note that the `ignore` globs need the same treatment as the path, or `fnmatch` raises the same
str/bytes `TypeError` a line later.

### 3. `filetote._get_artifact_destination` — `TypeError` on `DefaultTemplateFunctions`

```
File "beetsplug/filetote.py", line 516, in _get_artifact_destination
  template_functions = DefaultTemplateFunctions().functions()
TypeError: DefaultTemplateFunctions.__init__() missing 2 required positional arguments: 'item' and 'lib'
```

beets 2.13 dropped the `None` defaults for `item`/`lib`. The `None` *handling* is still there
(`tmpl_aunique`/`tmpl_sunique` short-circuit to `""`), so passing them explicitly preserves
current behavior — though that does mean `%aunique` stays empty in filetote path templates,
which you may want to revisit separately.

### Reproduction

Synthetic 2-disc album (`disctotal=2`), album-level artifacts in the parent dir and one per disc,
imported with `copy: yes`, autotag off, into a throwaway library. Fails at #1; with #1 patched,
fails at #2; with #2 patched, fails at #3 during `cli_exit`. With all three, the import completes
and every artifact lands correctly (album-level and per-disc, including the expected
`notes.txt`/`notes.1.txt` collision handling). A single-disc import with a non-ASCII artifact
name and an ignore glob also still behaves.

I notice the tox matrix currently runs 2.4–2.12 plus master — 2.13 falling between the pinned
range and master would explain why all three slipped through.

### What I'm running locally

Posting these for diagnosis only, **not** as a proposed fix — they're minimal shims to unblock my
own imports, they have no tests, and at least one of them cuts against the direction of the
codebase. Happy to open a PR if useful, but you'll likely want different fixes:

```diff
 def is_multidisc(path_name: Path) -> bool:
-    path_name_bytes = util.bytestring_path(path_name.name)
-
-    return any(pat.match(path_name_bytes) for pat in MULTIDISC_PATTERNS)
+    name_str: str = util.displayable_path(path_name.name)
+    name_bytes: bytes = util.bytestring_path(path_name.name)
+
+    return any(
+        pat.match(name_str if isinstance(pat.pattern, str) else name_bytes)
+        for pat in MULTIDISC_PATTERNS
+    )
```

```diff
 def discover_artifacts(...) -> list[Path]:
     artifacts: list[Path] = []
 
-    for root, _dirs, files in util.sorted_walk(source_path, ignore=ignore):
+    source_path_bytes: bytes = util.bytestring_path(source_path)
+    ignore_bytes: list[bytes] = [util.bytestring_path(p) for p in ignore]
+
+    for root, _dirs, files in util.sorted_walk(source_path_bytes, ignore=ignore_bytes):
```

```diff
-        template_functions = DefaultTemplateFunctions().functions()
+        template_functions = DefaultTemplateFunctions(None, None).functions()
```

Caveats on the above, so they're not taken at face value:

- The `discover_artifacts` shim encodes to bytes to satisfy the existing `root + PATH_SEP_BYTES +
  filename` loop body. That runs *against* the documented preference for `pathlib.Path` over other
  strategies — since `sorted_walk` accepts `str` fine, a str-native version is probably the fix you
  actually want.
- The `isinstance(pat.pattern, str)` check keeps compatibility both ways, but extending the existing
  `try`/`except ImportError` shim to pick up `MULTIDISC_BYTES_PATTERNS` would fit the file better.

Disclosure: the diagnosis and patches were AI-assisted. Everything above was verified by running it
against beets 2.13.1 rather than inferred — but review accordingly.

**Comment by Gwouigwoui** [comment]
> ### 2. `path_utils.discover_artifacts` — `AttributeError` in `sorted_walk`
> 
> ```
> File "beetsplug/path_utils.py", line 54, in discover_artifacts
>   for root, _dirs, files in util.sorted_walk(source_path, ignore=ignore)
> File "beets/util/__init__.py", line 253, in sorted_walk
>   sort_key = path.__class__.lower
> AttributeError: type object 'WindowsPath' has no attribute 'lower'
> ```
> 
> `sorted_walk` is now generic over `AnyStr` and no longer coerces its argument, so the `Path` it's handed flows through to `path.__class__.lower`. Verified directly against 2.13.1:
> argument 	result
> `Path` 	`AttributeError`
> `bytes` 	OK
> `str` 	OK
> 
> **This one isn't multi-disc specific.** `discover_artifacts` is called for every collection, so any import that reaches artifact discovery fails on 2.13 — multi-disc releases just hit `is_multidisc` first and crash earlier.
> 
> Note that the `ignore` globs need the same treatment as the path, or `fnmatch` raises the same str/bytes `TypeError` a line later.

This second issue also happens with the PosixPath object when using the mbsync plugin. Could it be tied to beets switching to using 'pathlib.Path'?

**Comment by ashprice** [comment]
I was working on some broad fixes related to this but ran out of time and don't think I'll get back to it in the next few weeks. Originally I started it on my own but I noticed arogl's PR #351 and thought it took a better approach so reworked what I was doing around it and had intended to open a PR to arogl's branch. It's mostly a rough sketch as opposed to something I'd consider mergeable; I haven't tested thoroughly. Current state is at: https://github.com/ashprice/beets-filetote/tree/pr-351-no-noise (no-noise is not a reference to arogl's work but to me including a lot of dependabot stuff originally that cluttered the commit history). 

The tests failing might be due to me doing the CI setup wrong, not sure.

**Comment by gtronset** [comment]
Thanks for reporting! I've been taking a look into this and am working on a fix.

**Comment by gtronset** [comment]
Deploy with fix is now available: https://github.com/gtronset/beets-filetote/releases/tag/v1.3.7
