### ISSUE TITLE
beets 2.8.0 - ImportError: cannot import name 'DefaultTemplateFunctions' from 'beets.library'

### ISSUE THREAD

**Issue by endcredits33** [gtronset/beets-filetote#281]
The plugin doesn't seem to work with beets 2.8.0, I'm getting the following error after updating from 2.7.1:

`ImportError: cannot import name 'DefaultTemplateFunctions' from 'beets.library'`

**Comment by GriekseEi** [comment]
Can confirm this applies for beets 2.9.0 too.

**Comment by mikeroll** [comment]
If you check your dependency tree, having beets >= 2.8.0 pulls in the old 1.0.3 version of the plugin, because it's last release to [advertise support for any 2.* version of beets](https://github.com/gtronset/beets-filetote/blob/v1.0.3/pyproject.toml#27).

Either way, it's [not compatible](https://github.com/gtronset/beets-filetote/blob/main/pyproject.toml#L27) with 2.8.0+ yet, just wanted to clarify that the exception does not actually come from the latest version.

I now have `beets-filetote >= 1.1.0` in my requirements to respect that constraint.

**Comment by mikeroll** [comment]
Okay I ignored the constraint with 
```toml
[tool.uv]
override-dependencies = ["beets >=2.9.0"]
```
and ran the latest filetote with the latest beets. So far nothing blew up, so it might be that just the package metadata needs to be updated.

**Comment by gtronset** [comment]
New release [v1.3.4](https://github.com/gtronset/beets-filetote/releases/tag/v1.3.4) is out and with the changes in https://github.com/gtronset/beets-filetote/pull/284 should prevent this going forward!
